language: python
python:
  - "2.7"
  - "3.4"

# command to install dependencies
install:
  - pip install -e .

script:
  - wooqi --seq-config testing/postfail_feature/tests/postfail_next_step.ini --sn wooqi_tests -s
  - ./run_wooqi_tests.sh
